### ISSUE TITLE
can't login or use the extension

### ISSUE THREAD

**Issue by alciobanita** [aquila-lab/superflex-vscode#26]
Hi there,

I can't use the extension in MS anymore. I tried uninstalling and installing it again, but i get everytime the same error: "Internal Server error". Can you help please?
![ise](https://github.com/user-attachments/assets/e12c22c0-1bfa-474f-997e-aa26576aaeee)

**Comment by aibek-yegemberdin** [comment]
Hello Andrei,

Thank you for bringing this to our attention! I looped in Boris, our CTO he will look into the issue and let you know about the next steps.

Thank you,
Aibek

Aibek Yegemberdin
Co-Founder of Superflex
LinkedIn | Book a Meeting

**Comment by aibek-yegemberdin** [comment]
Hi Andrei,

Thank you for bringing the issue to our attention. We sincerely apologize for the inconvenience caused by the downtime, which lasted for about 30 minutes. We’re pleased to inform you that everything has been fully resolved, and our systems are now up and running smoothly.

As a gesture of our apology for little downtime, I would like to offer you two weeks of the Individual Pro Plan free of charge. Please let me know if you'd like to proceed, and I will set it up right away.

Thank you for your patience and understanding!

Best regards,
Boris


Boris Janković
Co-Founder & CTO at  Superflex
LinkedIn  |  Book a Meeting
